#!/bin/sh
exec tail -n +3 "$0"
# A1-BSW (20260916_221948): a1_rt.sh tune rt-poll 가 생성. 원복: sudo rm /etc/grub.d/13_a1_bsw_rt_poll && sudo update-grub
menuentry 'A1-BSW 운용: Linux 6.8.1-1059-realtime + 격리 8-15 + idle=poll + intel_pstate=disable (부팅 후 iso_pm.sh eco 800, hk ondemand)' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'a1-bsw-rt-poll' {
	recordfail
	load_video
	gfxmode $linux_gfx_mode
	insmod gzio
	if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
	insmod part_gpt
	insmod ext2
	search --no-floppy --fs-uuid --set=root 3cb4c60d-1e8a-444b-8efc-612a444cc5b6
	echo	'Loading Linux 6.8.1-1059-realtime ...'
	linux	/boot/vmlinuz-6.8.1-1059-realtime root=UUID=3cb4c60d-1e8a-444b-8efc-612a444cc5b6 ro  quiet splash $vt_handoff isolcpus=managed_irq,domain,8-15 nohz_full=8-15 rcu_nocbs=8-15 rcu_nocb_poll irqaffinity=0-7,16-19 intel_idle.max_cstate=0 processor.max_cstate=0 nmi_watchdog=0 nosoftlockup skew_tick=1 idle=poll intel_pstate=disable cpufreq.default_governor=performance
	echo	'Loading initial ramdisk ...'
	initrd	/boot/initrd.img-6.8.1-1059-realtime
}
